version: '3.8'

services:
  elv-app:
    build: .
    container_name: elv-app
    network_mode: host
    volumes:
      - /opt/conf:/opt/conf
      - /opt/logs/elv:/app/logs
    environment:
      - TZ=Asia/Seoul
      - BASE_PATH=/app/data
      - LOG_HOME=/app/logs
    restart: on-failure